name: loop
ghc-options:
  - -fdefer-typed-holes
  # - -fdefer-type-errors
  - -O1
  - -Wall
  - -Wno-name-shadowing
default-extensions:
  - Strict

dependencies:
  - base
  - random
  - bytestring
  - bytestring-conversion
  - vector
  - generics-eot

executables:
  loop:
    main: main.hs
    source-dirs:
      - src

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec
      - HUnit
      - string-conversions
