name: song
ghc-options:
  - -fdefer-typed-holes
  - -O1
  - -Wall
  - -Wno-name-shadowing
default-extensions:
  - Strict

dependencies:
  - base
  - bytestring
  - bytestring-conversion
  - random
  - vector
  - transformers
  - loops-lib

executables:
  song:
    main: main.hs
    source-dirs:
      - src

benchmarks:
  benchmark:
    main: ../benchmark/Main.hs
    source-dirs:
      - src
    dependencies:
      - criterion
